name: CICD_Learning
on: ["push", "workflow_dispatch"]
jobs:
  Build:
    runs-on: ubuntu-latest
    env:
      NAME: Nagender
    steps:
      - name: Test steps
        env:
          NAME: Nagender
        run: echo "Hello $NAME"

      - name: Another Step
        run: echo "Hello ${{ env.NAME }}"
