name: CICD_Learning
on: ["push", "workflow_dispatch"]
jobs:
  Build:
    runs-on: ubuntu-latest
    env:
      NAME: Nagender
    steps:
      - name: Create a file
        run: echo "I won't live long" > my_file.txt

      - name: Upload Artifact
        uses: actions/upload-artifact@v7
        with:
          name: my-artifact
          path: my_file.txt

      - name: Download Artifact
        uses: actions/download-artifact@v8
        with:
          name: my-artifact

      - name: View the artifact
        run: cat my_file.txt
